spring:
  application:
    name: "umc9th2"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 클래스 이름
    url: ${DB_URL} # jdbc:mysql://localhost:3306/{데이터베이스명}
    username: ${DB_USER} # MySQL 유저 이름
    password: ${DB_PW} # MySQL 비밀번호

  jpa:
    database: mysql # 사용할 데이터베이스 유형 지정 (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate에서 사용할 MySQL 방언(dialect) 설정
    show-sql: true # 실행된 SQL 쿼리를 콘솔에 출력할지 여부 설정
    hibernate:
      ddl-auto: create # 애플리케이션 실행 시 데이터베이스 스키마의 상태를 설정
    properties:
      hibernate:
        format_sql: true # 출력되는 SQL 쿼리를 보기 좋게 포맷팅

  profiles:
    active: local   # 기본은 로컬 환경

server:
  port: 8080

jwt:
  token:
    secretKey: ZGh3YWlkc2F2ZXdhZXZ3b2EgMTM5ZXUgMDMxdWMyIHEyMiBAIDAgKTJFVio=
    expiration:
      access: 14400000


---
spring:
  config:
    activate:
      on-profile: local
  discord:
    webhook:
      url: ""  # 로컬은 비워둔다 (알림 안 감)
---
spring:
  config:
    activate:
      on-profile: dev
  discord:
    webhook:
      url: ${DISCORD_WEBHOOK_URL}  # 개발 서버용 Webhook URL


#  h2:
#    console:
#      enabled: true
#      path: /h2-console

